#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from monitoring_rqt_plot.plot import Plot

plugin = 'monitoring_rqt_plot.plot.Plot'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=Plot.add_arguments))
